# Generated by Django 2.2 on 2021-12-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
