# Generated by Django 2.2 on 2021-12-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20211209_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deletable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='deletable',
            field=models.BooleanField(default=False),
        ),
    ]
